name: G-Lobby
main: zomarrd\ghostly\Ghostly
api: 4.0.0
description: Ghostly Lobby Plugin
version: 4.0.0
author: zOmArRD

permissions:
  ghostly.command.npc:
    default: op
  ghostly.command.lang.set-other:
    default: op
  ghostly.command.server:
    default: op
  ghostly.global-mute.bypass:
    default: op
  ghostly.command.global-mute:
    default: op
  ghostly.build:
    default: op
  ghostly.server.connect-whitelisted:
    default: op
  ghostly.server.join-bypass:
    default: op
  ghostly.proxy-bypass:
    default: op