<?php
/*
 * Created by PhpStorm.
 *
 * User: zOmArRD
 * Date: 24/12/2021
 *
 * Copyright © 2021 GhostlyMC Network - All Rights Reserved.
 */
declare(strict_types=1);

namespace zomarrd\ghostly;

use AttachableLogger;
use pocketmine\event\Listener;
use pocketmine\network\mcpe\convert\SkinAdapterSingleton;
use pocketmine\plugin\PluginBase;
use pocketmine\plugin\PluginLogger;
use zomarrd\ghostly\config\ConfigManager;
use zomarrd\ghostly\mysql\MySQL;
use zomarrd\ghostly\player\skin\MojangAdapter;

final class Ghostly extends PluginBase
{
	public static Ghostly $instance;
	public static AttachableLogger $logger;

	protected function onLoad(): void
	{
		self::$instance = $this;
		self::$logger = $this->getLogger();
		SkinAdapterSingleton::set(new MojangAdapter());
		new ConfigManager();
		MySQL::createTables();
	}

	protected function onEnable(): void
	{
		$prefix = PREFIX;



		self::$logger->notice('§c' . <<<INFO


         $$$$$$\  $$\                             $$\     $$\           $$\      $$\  $$$$$$\  
        $$  __$$\ $$ |                            $$ |    $$ |          $$$\    $$$ |$$  __$$\ 
        $$ /  \__|$$$$$$$\   $$$$$$\   $$$$$$$\ $$$$$$\   $$ |$$\   $$\ $$$$\  $$$$ |$$ /  \__|
        $$ |$$$$\ $$  __$$\ $$  __$$\ $$  _____|\_$$  _|  $$ |$$ |  $$ |$$\$$\$$ $$ |$$ |      
        $$ |\_$$ |$$ |  $$ |$$ /  $$ |\$$$$$$\    $$ |    $$ |$$ |  $$ |$$ \$$$  $$ |$$ |      
        $$ |  $$ |$$ |  $$ |$$ |  $$ | \____$$\   $$ |$$\ $$ |$$ |  $$ |$$ |\$  /$$ |$$ |  $$\ 
        \$$$$$$  |$$ |  $$ |\$$$$$$  |$$$$$$$  |  \$$$$  |$$ |\$$$$$$$ |$$ | \_/ $$ |\$$$$$$  |
         \______/ \__|  \__| \______/ \_______/    \____/ \__| \____$$ |\__|     \__| \______/ 
                                                              $$\   $$ |                       
                                                              \$$$$$$  |                       
                                                               \______/         
                                                               
         $prefix §fCreated by zOmArRD :)                                                                     
INFO
		);
	}

	protected function onDisable(): void
	{
		parent::onDisable(); // TODO: Change the autogenerated stub
	}

	public static function getInstance(): Ghostly
	{
		return self::$instance;
	}

	/**
	 * @param Listener[] $listeners
	 *
	 * @return void
	 */
	public function registerListener(array $listeners): void
	{
		$manager = $this->getServer()->getPluginManager();
		foreach ($listeners as $listener) {
			$manager->registerEvents($listener, $this);
		}
	}
}